# Atividade Prática — Aula 2: Pandas Essencial

Nesta atividade, você vai aplicar os conceitos da aula para explorar um dataset de vendas, fazer um **check-up inicial**, selecionar colunas relevantes, criar **filtros de negócio**, construir **rankings** e transformar resultados em **interpretação gerencial**.

**Dataset:** `vendas_dataviz_aula2.csv`

## Objetivos da atividade
- Ler e inspecionar um dataset com Pandas
- Entender a diferença entre DataFrame e Series
- Verificar tamanho, tipos e possíveis problemas de qualidade
- Selecionar apenas as colunas importantes para análise
- Filtrar dados com uma e múltiplas condições
- Criar rankings com `sort_values`, `nlargest` e `nsmallest`
- Interpretar resultados em linguagem de negócio

## 1. Importação das bibliotecas

Importe as bibliotecas necessárias para a atividade.
- `pandas`
- `numpy`
- `matplotlib.pyplot` (caso queira visualizar resultados)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 2. Leitura do dataset

Leia o arquivo `vendas_dataviz_aula2.csv` em um DataFrame chamado `df`.
Depois, exiba as 5 primeiras linhas.

In [3]:
df = pd.read_csv('../data/vendas_dataviz_aula2.csv')
df.head()

,data,produto,categoria,estado,canal,vendas,quantidade,preco_unitario,custo,lucro,avaliacao_cliente
0,2024-04-12,Mouse Gamer,Periféricos,RJ,Marketplace,562.26,3,187.42,97.70,269.16,4.6
1,2024-05-01,Headset,Áudio,ES,MarketPlace,1124.08,4,281.02,144.77,545.00,3.8
2,2024-10-03,Teclado Mecânico,Periféricos,SP,Marketplace,2515.73,7,359.39,153.66,1440.11,4.3
3,2024-07-06,Webcam HD,Periféricos,SP,Marketplace,596.76,3,198.92,125.09,221.49,4.3
4,2024-02-24,Smartwatch,Telefonia,RJ,Loja Física,3908.08,4,977.02,666.26,1243.04,4.4

## 3. Anatomia dos dados: DataFrame e Series

### Questão 1
Explique, com base no que foi visto em aula:
1. O que é um **DataFrame**?
2. O que é uma **Series**?
3. Mostre no código uma coluna isolada do DataFrame.

In [12]:
print("\nO que é DataFrame")
print("Um DataFrame é a estrutura tabular (tabela inteira, com linhas e colunas), principal do pandas, semelhante a uma planilha ou tabela de banco de dados, com linhas e colunas.")

print("\nO que é Serie")
print("Uma Series é uma estrutura unidimensional do pandas, uma única coluna isolada de dados.")
print("-----------------------------------------------------------------------------------------------------\n")

tipo_df = type(df)
serie_produto = df["produto"]
tipo_serie = type(serie_produto)


print("Primeiras linhas da coluna produto: ")
print(serie_produto.head())


print("\ncoluna produto:", serie_produto.value_counts())

O que é DataFrame
Um DataFrame é a estrutura tabular (tabela inteira, com linhas e colunas), principal do pandas, semelhante a uma planilha ou tabela de banco de dados, com linhas e colunas.

O que é Serie
Uma Series é uma estrutura unidimensional do pandas, uma única coluna isolada de dados.
-----------------------------------------------------------------------------------------------------

Primeiras linhas da coluna produto:
0         Mouse Gamer
1             Headset
2    Teclado Mecânico
3           Webcam HD
4          Smartwatch
Name: produto, dtype: str

coluna produto: produto
Caixa de Som        58
Headset             55
Smartwatch          51
Mouse Gamer         50
Teclado Mecânico    46
Smartphone X        42
Tablet Plus         41
Webcam HD           39
Notebook Pro        34
Monitor 27          34
Name: count, dtype: int64

## 4. Check-up inicial do dataset

Um analista profissional sempre começa verificando o tamanho, a estrutura e a qualidade inicial dos dados.

### Questão 2
Use:
- `df.shape`
- `df.info()`
- `df.dtypes`

Depois responda:
1. Quantas linhas e colunas existem?
2. Quais colunas parecem numéricas?
3. Há sinais de valores ausentes?
4. Existe alguma coluna com tipo inadequado?

In [13]:
df.shape

(450, 11)

In [17]:
df.info()

print("\nColunas com nulos:")
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   data               450 non-null    str
 1   produto            450 non-null    str
 2   categoria          450 non-null    str
 3   estado             449 non-null    str
 4   canal              450 non-null    str
 5   vendas             450 non-null    str
 6   quantidade         450 non-null    int64
 7   preco_unitario     450 non-null    float64
 8   custo              450 non-null    float64
 9   lucro              450 non-null    float64
 10  avaliacao_cliente  448 non-null    float64
dtypes: float64(4), int64(1), str(6)
memory usage: 38.8 KB

Colunas com nulos:
data                 0
produto              0
categoria            0
estado               1
canal                0
vendas               0
quantidade           0
preco_unitario       0
custo                0
lucro                0
avaliacao_cliente    2
dtype: int64

In [15]:
df.dtypes

data                     str
produto                  str
categoria                str
estado                   str
canal                    str
vendas                   str
quantidade             int64
preco_unitario       float64
custo                float64
lucro                float64
avaliacao_cliente    float64
dtype: object

In [ ]:
is_na = df.isna().sum()
qnt_estados = df['estado'].value_counts(dropna=False)
qnt_avaliacao = df['avaliacao_cliente'].value_counts(dropna=False)

print(qnt_estados)
print()
print(qnt_avaliacao)

# 1. Quantas linhas e colunas existem?
print("\nResp. 01: \n450 Linhas e 11 Colunas")

# 2. Quais colunas parecem numéricas?
print("\nResp. 02: \nAs Colunas Quantidade, preco_unitario, custo, lucro e avaliacao_cliente são colunas numericas")

# 3. Há sinais de valores ausentes?
print("\nResp. 03: \nA sinais de valores ausente, na coluna Estado e coluna avaliacao_cliente.")


# 4. Existe alguma coluna com tipo inadequado?
print("\nResp. 04: \n Não sei se é essa a resposta mas o RJ tem q fora do padrão")

estado
ES     62
SP     52
BA     52
GO     49
PE     48
SC     42
MG     39
RS     38
RJ     36
PR     30
rj      1
NaN     1
Name: count, dtype: int64

avaliacao_cliente
3.9    43
4.3    39
4.0    38
4.1    37
3.8    36
4.2    34
4.5    30
4.4    27
4.6    20
3.6    19
3.5    19
3.7    19
4.7    17
4.8    13
5.0    11
4.9    10
3.4     9
3.3     8
3.0     7
3.1     4
3.2     3
2.7     3
NaN     2
2.8     1
2.9     1
Name: count, dtype: int64

Resp. 01:
450 Linhas e 11 Colunas

Resp. 02:
As Colunas Quantidade, preco_unitario, custo, lucro e avaliacao_cliente são colunas numericas

Resp. 03:
A sinais de valores ausente, na coluna Estado e coluna avaliacao_cliente.

Resp. 04:

## 5. Inspeção de problemas de qualidade

Na aula, vimos que dashboards podem falhar por causa de dados mal preparados.

### Questão 3
Investigue:
- valores nulos
- categorias inconsistentes
- números armazenados como texto
- valores infinitos

Dica:
- `df.isna().sum()`
- `df['canal'].value_counts(dropna=False)`
- `df['estado'].value_counts(dropna=False)`
- `np.isinf(...)`

In [ ]:
df.isna().sum()

data                 255
produto               10
categoria              4
estado                11
canal                  6
vendas               450
quantidade            11
preco_unitario       449
custo                449
lucro                447
avaliacao_cliente     24
dtype: int64

In [32]:
df.nunique()

data                 255
produto               10
categoria              4
estado                11
canal                  6
vendas               450
quantidade            11
preco_unitario       449
custo                449
lucro                447
avaliacao_cliente     24
dtype: int64

In [34]:
print(df['produto'].value_counts(dropna=False))
print()
print(df['categoria'].value_counts(dropna=False))
print()
print(df['estado'].value_counts(dropna=False))
print()
print(df['canal'].value_counts(dropna=False))

produto
Caixa de Som        58
Headset             55
Smartwatch          51
Mouse Gamer         50
Teclado Mecânico    46
Smartphone X        42
Tablet Plus         41
Webcam HD           39
Notebook Pro        34
Monitor 27          34
Name: count, dtype: int64

categoria
Periféricos    135
Telefonia      134
Áudio          113
Informática     68
Name: count, dtype: int64

estado
ES     62
SP     52
BA     52
GO     49
PE     48
SC     42
MG     39
RS     38
RJ     36
PR     30
rj      1
NaN     1
Name: count, dtype: int64

canal
Marketplace    152
Online         148
Loja Física    147
MarketPlace      1
online           1
ONLINE           1
Name: count, dtype: int64

In [20]:
df['estado'].value_counts(dropna=False)

estado
ES     62
SP     52
BA     52
GO     49
PE     48
SC     42
MG     39
RS     38
RJ     36
PR     30
rj      1
NaN     1
Name: count, dtype: int64

In [21]:
# Verifique se há valores infinitos na coluna lucro
pd.Series(np.isinf(pd.to_numeric(df['lucro'], errors='coerce'))).value_counts(dropna=False)

lucro
False    448
True       2
Name: count, dtype: int64

## 6. Selecionando o que importa

Nem toda análise precisa de todas as colunas. Vamos criar um recorte mais focado para responder perguntas de negócio.

### Questão 4
Crie um novo DataFrame chamado `df_dash` contendo apenas as colunas:
- `data`
- `estado`
- `canal`
- `produto`
- `categoria`
- `vendas`
- `lucro`

Use `.copy()` para evitar problemas futuros.

In [36]:
cols_dashboard = ['data', 'estado', 'canal', 'produto', 'categoria', 'vendas', 'lucro']
df_dash = df[cols_dashboard].copy()
df_dash.head()

,data,estado,canal,produto,categoria,vendas,lucro
0,2024-04-12,RJ,Marketplace,Mouse Gamer,Periféricos,562.26,269.16
1,2024-05-01,ES,MarketPlace,Headset,Áudio,1124.08,545.00
2,2024-10-03,SP,Marketplace,Teclado Mecânico,Periféricos,2515.73,1440.11
3,2024-07-06,SP,Marketplace,Webcam HD,Periféricos,596.76,221.49
4,2024-02-24,RJ,Loja Física,Smartwatch,Telefonia,3908.08,1243.04

## 7. Preparação mínima para análise

Algumas colunas podem precisar de ajuste antes de ordenar e agregar.

### Questão 5
1. Converta a coluna `data` para formato de data.
2. Crie uma coluna `mes` a partir da data.
3. Tente converter `vendas` para numérico, tratando possíveis textos.
4. Crie uma coluna chamada `vendas_num`.

In [37]:
df_dash['data'] = pd.to_datetime(df_dash['data'], errors='coerce')
df_dash['mes'] = df_dash['data'].dt.to_period('M')

# Limpeza simples para a coluna vendas (remove símbolo R$, espaços e troca vírgula decimal)
vendas_limpa = (
    df_dash['vendas']
    .astype(str)
    .str.replace('R\$', '', regex=True)
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
    .str.strip()
)

df_dash['vendas_num'] = pd.to_numeric(vendas_limpa, errors='coerce')
df_dash.head()

<>:8: SyntaxWarning: invalid escape sequence '\$'
<>:8: SyntaxWarning: invalid escape sequence '\$'
C:\Users\SamuelEliasRocha\AppData\Local\Temp\ipykernel_31888\1170284534.py:8: SyntaxWarning: invalid escape sequence '\$'
  .str.replace('R\$', '', regex=True)

,data,estado,canal,produto,categoria,vendas,lucro,mes,vendas_num
0,2024-04-12,RJ,Marketplace,Mouse Gamer,Periféricos,562.26,269.16,2024-04,56226.0
1,2024-05-01,ES,MarketPlace,Headset,Áudio,1124.08,545.00,2024-05,112408.0
2,2024-10-03,SP,Marketplace,Teclado Mecânico,Periféricos,2515.73,1440.11,2024-10,251573.0
3,2024-07-06,SP,Marketplace,Webcam HD,Periféricos,596.76,221.49,2024-07,59676.0
4,2024-02-24,RJ,Loja Física,Smartwatch,Telefonia,3908.08,1243.04,2024-02,390808.0

## 8. Filtragem simples: recorte de negócio

Na aula, vimos o exemplo de filtrar apenas o estado do Rio de Janeiro.

### Questão 6
Crie um DataFrame `df_rj` contendo apenas registros do estado `RJ`.
Depois responda:
1. Quantos registros existem nesse recorte?
2. Qual a soma de vendas no RJ?

In [38]:
df_rj = df_dash[df_dash['estado'] == 'RJ']
df_rj.shape, df_rj['vendas_num'].sum()

((36, 9), np.float64(13161085.0))

## 9. Filtragem com múltiplas condições

Agora faça um recorte mais profissional: apenas vendas do estado do RJ no canal Online.

### Questão 7
Faça esse filtro de duas formas:
1. Usando operadores lógicos com `&`
2. Usando `query()`

In [39]:
df_rj_online = df_dash[(df_dash['estado'] == 'RJ') & (df_dash['canal'] == 'Online')]
df_rj_online.head()

,data,estado,canal,produto,categoria,vendas,lucro,mes,vendas_num
114,2024-10-26,RJ,Online,Mouse Gamer,Periféricos,378.4,185.94,2024-10,3784.0
173,2024-04-12,RJ,Online,Webcam HD,Periféricos,924.48,418.04,2024-04,92448.0
211,2024-12-31,RJ,Online,Caixa de Som,Áudio,3305.2,1361.44,2024-12,33052.0
222,2024-12-17,RJ,Online,Teclado Mecânico,Periféricos,1996.05,1105.55,2024-12,199605.0
243,2024-04-23,RJ,Online,Tablet Plus,Telefonia,10065.8,2142.15,2024-04,100658.0

In [40]:
df_rj_online_q = df_dash.query("estado == 'RJ' and canal == 'Online'")
df_rj_online_q.head()

,data,estado,canal,produto,categoria,vendas,lucro,mes,vendas_num
114,2024-10-26,RJ,Online,Mouse Gamer,Periféricos,378.4,185.94,2024-10,3784.0
173,2024-04-12,RJ,Online,Webcam HD,Periféricos,924.48,418.04,2024-04,92448.0
211,2024-12-31,RJ,Online,Caixa de Som,Áudio,3305.2,1361.44,2024-12,33052.0
222,2024-12-17,RJ,Online,Teclado Mecânico,Periféricos,1996.05,1105.55,2024-12,199605.0
243,2024-04-23,RJ,Online,Tablet Plus,Telefonia,10065.8,2142.15,2024-04,100658.0

## 10. Priorização: rankings

Gestores raramente leem tabelas enormes. Eles querem os **Top N**.

### Questão 8
Gere:
1. Os 10 registros com maior valor de `vendas_num`
2. Os 10 registros com maior `lucro`
3. Os 5 registros com menor `lucro`

Observe se aparece algum valor suspeito.

In [41]:
top10_vendas = df_dash.sort_values('vendas_num', ascending=False).head(10)
top10_vendas

,data,estado,canal,produto,categoria,vendas,lucro,mes,vendas_num
321,2024-08-18,SP,Loja Física,Notebook Pro,Informática,36140.72,10319.12,2024-08,3614072.0
183,2024-12-14,ES,Online,Notebook Pro,Informática,33212.83,13556.90,2024-12,3321283.0
56,2024-09-06,PE,Online,Notebook Pro,Informática,27867.72,9411.00,2024-09,2786772.0
319,2024-05-08,SC,Marketplace,Notebook Pro,Informática,21573.95,6869.60,2024-05,2157395.0
132,2024-08-05,PR,Loja Física,Notebook Pro,Informática,20352.96,8103.88,2024-08,2035296.0
387,2024-12-26,ES,Online,Tablet Plus,Telefonia,19061.82,5200.11,2024-12,1906182.0
74,2024-10-01,PR,Loja Física,Notebook Pro,Informática,18782.88,5744.80,2024-10,1878288.0
245,2024-12-26,SP,Marketplace,Smartphone X,Telefonia,18417.28,3773.84,2024-12,1841728.0
216,2024-07-22,SC,Online,Notebook Pro,Informática,17715.88,5747.00,2024-07,1771588.0
368,2024-05-29,SP,Online,Smartphone X,Telefonia,17631.48,5392.08,2024-05,1763148.0

In [42]:
# Primeiro garantimos que lucro esteja numérico
df_dash['lucro_num'] = pd.to_numeric(df_dash['lucro'], errors='coerce')

top10_lucro = df_dash.nlargest(10, 'lucro_num')
top10_lucro

,data,estado,canal,produto,categoria,vendas,lucro,mes,vendas_num,lucro_num
199,2024-02-06,ES,Online,Caixa de Som,Áudio,792.12,inf,2024-02,79212.0,inf
449,2024-06-10,SP,Marketplace,Teclado Mecânico,Periféricos,1818.06,inf,2024-06,181806.0,inf
183,2024-12-14,ES,Online,Notebook Pro,Informática,33212.83,13556.90,2024-12,3321283.0,13556.90
321,2024-08-18,SP,Loja Física,Notebook Pro,Informática,36140.72,10319.12,2024-08,3614072.0,10319.12
56,2024-09-06,PE,Online,Notebook Pro,Informática,27867.72,9411.00,2024-09,2786772.0,9411.00
442,2024-02-21,PR,Loja Física,Notebook Pro,Informática,19782.0,8546.28,2024-02,197820.0,8546.28
132,2024-08-05,PR,Loja Física,Notebook Pro,Informática,20352.96,8103.88,2024-08,2035296.0,8103.88
319,2024-05-08,SC,Marketplace,Notebook Pro,Informática,21573.95,6869.60,2024-05,2157395.0,6869.60
110,2024-06-28,BA,Loja Física,Smartphone X,Telefonia,16138.55,6519.65,2024-06,1613855.0,6519.65
109,2024-09-20,PE,Marketplace,Tablet Plus,Telefonia,14602.02,6151.92,2024-09,1460202.0,6151.92

In [ ]:
bottom5_lucro = df_dash.nsmallest(5, 'lucro_num')
bottom5_lucro

## 11. Ranking por produto

Agora vamos sair do nível do registro e pensar em **resultado por produto**.

### Questão 9
Agrupe por produto e calcule:
- soma de vendas
- soma de lucro

Depois:
1. Mostre os 10 produtos mais lucrativos
2. Interprete o resultado em linguagem de negócio

In [ ]:
ranking_produtos = (
    df_dash.groupby('produto', dropna=False)
    .agg(
        vendas_total=('vendas_num', 'sum'),
        lucro_total=('lucro_num', 'sum')
    )
    .sort_values('lucro_total', ascending=False)
)

ranking_produtos.head(10)

## 12. Ranking por estado e canal

### Questão 10
Crie dois rankings:
1. Estados com maior receita total
2. Canais com maior lucro total

Depois escreva uma interpretação curta para cada ranking.

In [ ]:
ranking_estados = (
    df_dash.groupby('estado', dropna=False)['vendas_num']
    .sum()
    .sort_values(ascending=False)
)

ranking_canais = (
    df_dash.groupby('canal', dropna=False)['lucro_num']
    .sum()
    .sort_values(ascending=False)
)

ranking_estados, ranking_canais

## 13. Análise temporal simples

### Questão 11
Agrupe os dados por `mes` e calcule a receita total mensal.
Depois responda:
1. Há meses de maior desempenho?
2. Existe indício de sazonalidade?

In [ ]:
receita_mensal = (
    df_dash.groupby('mes')['vendas_num']
    .sum()
    .sort_index()
)

receita_mensal

In [ ]:
receita_mensal.plot(kind='bar', figsize=(12,4), title='Receita mensal')
plt.ylabel('Receita')
plt.show()

## 14. A última milha: interpretação

Na aula, vimos que um analista não entrega apenas tabela — entrega **decisão**.

### Questão 12
Com base nos resultados do notebook, escreva interpretações gerenciais para:
1. O produto mais lucrativo
2. O estado com maior receita
3. O canal com maior lucro
4. Um possível problema de qualidade encontrado

## 15. Desafio extra (opcional)

Faça uma limpeza adicional do dataset:
- padronize valores de `canal` (`online`, `ONLINE`, `MarketPlace`, etc.)
- padronize `estado` (`rj` -> `RJ`)
- substitua infinitos em `lucro_num` por `NaN`
- trate valores ausentes como julgar adequado

Depois gere novamente os rankings e compare os resultados.

In [ ]:
# Escreva sua solução aqui

## 16. Entrega esperada

Seu notebook deve demonstrar:
- organização
- comentários explicativos
- código legível
- interpretação de negócio

### Fechamento
Ao terminar, salve o notebook com suas respostas e envie junto com o arquivo CSV utilizado.