# Atividade Prática — Aula 3: Limpeza, Preparação e Qualidade dos Dados com Pandas

Esta atividade foi construída com base nos slides da Aula 3, que destacam a **limpeza como a fundação invisível** de qualquer dashboard confiável. O objetivo aqui não é apenas "fazer funcionar", mas tomar decisões conscientes sobre tipos, valores ausentes, duplicidades, variáveis derivadas e exportação da base limpa. fileciteturn2file0

## Regras desta atividade
- Você deve **construir os códigos**.
- O notebook orienta os passos, mas não entrega as soluções prontas.
- Sempre que fizer uma decisão de limpeza, **documente o porquê** em comentário ou célula markdown.
- Ao final, exporte uma base limpa para uso nas próximas aulas.

## Dataset desta atividade
Arquivo bruto: `vendas_brasil_aula3_bruto.csv`

## 1. Preparação do ambiente

Importe as bibliotecas necessárias para trabalhar com:
- leitura de dados
- tratamento de nulos
- identificação de infinitos
- exportação do resultado final

**Sugestão:** Pandas e NumPy já resolvem toda a atividade.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 2. Leitura da base bruta

Leia o arquivo `vendas_brasil_aula3_bruto.csv` em um DataFrame chamado `df`.

Depois:
1. Exiba as primeiras linhas
2. Exiba as últimas linhas
3. Observe visualmente se já existem sinais de sujeira

In [2]:
df = pd.read_csv('../data/vendas_brasil_aula3_bruto.csv')
df.head()

,pedido_id,data,uf,canal,categoria,produto,cliente_id,quantidade,receita,lucro,observacao
0,1000,2024/04/29,SP,Loja Física,Informática,Notebook Pro,C134,1,4535.11,1289.83,ok
1,1001,2024-06-17,PR,NaN,Informática,Notebook Pro,C106,1,4005.59,541.36,entrega rápida
2,1002,2024-05-27,PR,Marketplace,Periféricos,Teclado Mecânico,C131,1,309.02,128.26,entrega rápida
3,1003,2024-07-08,SP,Marketplace,Informática,Notebook Pro,C148,2,7943.78,1574.09,ok
4,1004,2024-05-20,RS,Online,Informática,Notebook Pro,C105,5,19926.65,4281.84,ok

In [ ]:
# Exibe as ultimas linhas
df.tail()

,pedido_id,data,uf,canal,categoria,produto,cliente_id,quantidade,receita,lucro,observacao
223,1180,2024-03-11,SC,Loja Física,Telefonia,Smartphone X,C158,1,2563.44,415.42,NaN
224,1015,2024-02-26,RS,Online,Informática,Notebook Pro,C102,3,15011.49,NaN,cliente premium
225,1115,2024-07-29,MG,Loja Física,Informática,Notebook Pro,C144,3,12566.04,2879.76,NaN
226,1172,2024-11-11,ES,Loja Física,Informática,Notebook Pro,C128,3,13154.04,3408.22,entrega rápida
227,1209,2024-05-27,MG,Marketplace,Áudio,Caixa de Som,C121,2,810.2,282.52,NaN

## 3. Check-up inicial do dataset

Com base no checklist de um dataset "clean" apresentado na aula, faça um diagnóstico inicial da base. fileciteturn2file0

### Sua missão
Use comandos que permitam responder:
- Qual é o tamanho da base?
- Quais são os tipos atuais das colunas?
- Existem valores nulos?
- Há colunas com tipo inadequado?
- Há algo que pareça impedir análises confiáveis?

In [14]:
# Faça aqui o check-up inicial: shape, info, dtypes, isna, etc.
shape_df = df.shape
tipos_df = df.dtypes
nulos_df = df.isna().sum()

print("Shape:", shape_df)
print("Total de Linhas:", shape_df[0])
print("Total de Colunas:", shape_df[1])

print("\nTipos das colunas:")
print(tipos_df)

print("\nNulos por coluna:")
print(nulos_df)
print()
df.info()


print('\n\n--------------------------------------------------------------------------------------------------------------------')

Shape: (228, 11)
Total de Linhas: 228
Total de Colunas: 11

Tipos das colunas:
pedido_id              int64
data          datetime64[us]
uf                       str
canal                    str
categoria                str
produto                  str
cliente_id               str
quantidade             int64
receita              float64
lucro                float64
observacao               str
dtype: object

Nulos por coluna:
pedido_id       0
data          224
uf              5
canal           5
categoria       5
produto         0
cliente_id      0
quantidade      0
receita         5
lucro           6
observacao     50
dtype: int64

<class 'pandas.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pedido_id   228 non-null    int64
 1   data        4 non-null      datetime64[us]
 2   uf          223 non-null    str
 3   canal       223 non-null    str
 4   categoria   223 non-null    str
 5   produto     228 non-null    str
 6   cliente_id  228 non-null    str
 7   quantidade  228 non-null    int64
 8   receita     223 non-null    float64
 9   lucro       222 non-null    float64
 10  observacao  178 non-null    str
dtypes: datetime64[us](1), float64(2), int64(2), str(6)
memory usage: 19.7 KB


--------------------------------------------------------------------------------------------------------------------

## 4. Batalha 1 — A tirania dos tipos de dados

Nos slides, vimos que datas não podem ser tratadas como texto e que números em formato string quebram análises. fileciteturn2file0

### Tarefa
Converta corretamente, quando fizer sentido:
- `data`
- `receita`
- `lucro`
- `quantidade`

### Orientação
- Investigue valores estranhos antes de converter
- Pense no uso de `errors='coerce'`
- Registre em markdown ou comentário quais problemas encontrou

In [ ]:
# Explore valores problemáticos e faça as conversões de tipo
def to_numeric_br(serie):
    serie_limpa = (
        serie.astype(str)
        .str.strip()
        .str.replace("R$", "", regex=False)
        .str.replace("r$", "", regex=False)
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
        .replace({"": np.nan, "Nan": np.nan, "None": np.nan})
    )
    return pd.to_numeric(serie_limpa, errors="coerce")

# difinindo o formato da data
print("Amostras de data:")
print(df["data"].astype(str).drop_duplicates().head(10))
print()

print("Amostras de receita:")
print(df["receita"].astype(str).drop_duplicates().head(10))
print()

if "lucro" in df.columns:
    print("Amostras de lucro:")
    print(df["lucro"].astype(str).drop_duplicates().head(10))
    print()

print("Amostras de quantidade:")
print(df["quantidade"].astype(str).drop_duplicates().head(10))



print(df.dtypes)
print()
print(df.head())

### Problemas encontrados
# A coluna `data` possui valores em formato textual.
# As colunas `receita` e `lucro` continham números como texto, com símbolo `R$` e separadores decimais/milhar.
# Foi necessário limpar esses caracteres antes da conversão.
# O uso de `errors='coerce'` evita erro de execução e transforma valores inválidos em `NaN`.
# A coluna `quantidade` foi convertida para tipo numérico, também com `errors='coerce'`, para tratar possíveis valores não numéricos.

### Colunas críticas identificadas
# `data`: contém valores ausentes (NaN)
# `receita`: valores incorretos após conversão e possíveis NaN
# `lucro`: mesma situação da receita
# `quantidade`: aparentemente consistente, mas requer validação

#### data
# remoção de linhas com valores nulos
# Justificativa: a data é essencial para análise temporal e não pode ser inferida com segurança

#### receita
# correção da conversão e remoção de valores nulos
# Justificativa: é uma variável central de negócio, não sendo adequado imputar valores

#### lucro
# correção da conversão e manutenção inicial de nulos
# Justificativa: pode ser mantido caso não seja foco da análise; remoção apenas se necessário

#### quantidade
# conversão para numérico e possível imputação com mediana
# Justificativa: variável discreta onde imputação é aceitável e menos impactante

print('\n\n--------------------------------------------------------------------------------------------------------------------')

Amostras de data:
0      2024-04-29
1             NaN
17     2024-09-30
101    2024-10-21
Name: data, dtype: str

Amostras de receita:
0     45351100000000.0
1     40055900000000.0
2      3090200000000.0
3     79437800000000.0
4    199266500000000.0
5      7529400000000.0
6      1154600000000.0
7      6938500000000.0
8      3890800000000.0
9      3164100000000.0
Name: receita, dtype: str

Amostras de lucro:
0    12898300000000.0
1     5413600000000.0
2     1282600000000.0
3    15740900000000.0
4    42818400000000.0
5     3757600000000.0
6      491000000000.0
7    13798400000000.0
8     1381900000000.0
9     1537300000000.0
Name: lucro, dtype: str

Amostras de quantidade:
0      1
3      2
4      5
6      4
10     3
119    6
Name: quantidade, dtype: str
pedido_id              int64
data          datetime64[us]
uf                       str
canal                    str
categoria                str
produto                  str
cliente_id               str
quantidade             int64
receita              float64
lucro                float64
observacao               str
dtype: object

   pedido_id       data  uf        canal    categoria           produto  \
0       1000 2024-04-29  SP  Loja Física  Informática      Notebook Pro
1       1001        NaT  PR          NaN  Informática      Notebook Pro
2       1002        NaT  PR  Marketplace  Periféricos  Teclado Mecânico
3       1003        NaT  SP  Marketplace  Informática      Notebook Pro
4       1004        NaT  RS       Online  Informática      Notebook Pro

  cliente_id  quantidade       receita         lucro      observacao
0       C134           1  4.535110e+13  1.289830e+13              ok
1       C106           1  4.005590e+13  5.413600e+12  entrega rápida
2       C131           1  3.090200e+12  1.282600e+12  entrega rápida
3       C148           2  7.943780e+13  1.574090e+13              ok
4       C105           5  1.992665e+14  4.281840e+13              ok


--------------------------------------------------------------------------------------------------------------------

### Reflexão curta
Explique:
1. Por que deixar `data` como texto pode quebrar análises temporais?
2. Por que deixar `receita` como string pode distorcer cálculos?

## 5. Batalha 2 — O enigma dos valores ausentes

A aula reforça que valores ausentes não devem ser tratados automaticamente; a decisão precisa ser justificada. fileciteturn2file0

### Tarefa
1. Mapeie os valores ausentes por coluna
2. Identifique quais colunas críticas têm nulos
3. Defina uma estratégia para cada caso:
   - remover linhas?
   - preencher?
   - manter?
4. Justifique cada escolha

### Dica
Evite decisões automáticas sem análise de contexto.

In [ ]:
# Investigue os nulos e aplique aqui sua estratégia de tratamento
nulos_antes = df.isna().sum()

colunas_criticas = [col for col in ["data", "receita", "uf", "canal", "produto"] if col in df.columns]
df_tratado_nulos = df.dropna(subset=colunas_criticas).copy()

if "categoria" in df_tratado_nulos.columns:
    df_tratado_nulos["categoria"] = df_tratado_nulos["categoria"].fillna("Não informado")

for col in ["quantidade", "custo_unitario", "preco_unitario"]:
    if col in df_tratado_nulos.columns:
        mediana_col = df_tratado_nulos[col].median()
        df_tratado_nulos[col] = df_tratado_nulos[col].fillna(mediana_col)

nulos_depois = df_tratado_nulos.isna().sum()

print("Nulos antes:")
print(nulos_antes)
print()
print("Nulos depois:")
print(nulos_depois)

### Tratamento de valores nulos

#### 1. Identificação
# As colunas com valores nulos identificadas foram:
    # `data` (224 nulos)
    # `receita` (5 nulos)
    # `uf` (5 nulos)
    # `canal` (5 nulos)
    # `categoria` (5 nulos)
    # `lucro` (6 nulos)
    # `observacao` (50 nulos)

#### 2. Estratégia adotada

# Colunas críticas (`data`, `receita`, `uf`, `canal`):
# Estratégia: remoção das linhas com valores nulos (`dropna`)
# Justificativa:
  # `data` é essencial para análises temporais
  # `receita` é uma métrica principal
  # `uf` e `canal` são importantes para segmentação
# Observação:
  # A remoção de 224 registros devido à ausência de `data` pode impactar o volume de dados disponível

# Coluna `categoria`:
# Estratégia: preenchimento com "Não informado"
# Justificativa:
  # Não é uma coluna crítica
  # Mantém os dados para análise sem perda significativa

# Colunas numéricas (`quantidade`, `custo_unitario`, `preco_unitario`):
# Estratégia: preenchimento com a mediana
# Justificativa:
  # A mediana é menos sensível a valores extremos (outliers)
  # Evita distorção nos dados

# Coluna `observacao`:
# Estratégia: manter valores nulos
# Justificativa:
  # Campo descritivo sem impacto direto nas análises quantitativas


print('\n\n--------------------------------------------------------------------------------------------------------------------')

Nulos antes:
pedido_id       0
data          224
uf              5
canal           5
categoria       5
produto         0
cliente_id      0
quantidade      0
receita         5
lucro           6
observacao     50
dtype: int64

Nulos depois:
pedido_id     0
data          0
uf            0
canal         0
categoria     0
produto       0
cliente_id    0
quantidade    0
receita       0
lucro         0
observacao    2
dtype: int64


--------------------------------------------------------------------------------------------------------------------

### Registro reflexivo
Escreva aqui sua justificativa para o tratamento dos nulos:
- Em quais colunas você removeu linhas?
- Em quais colunas você preencheu valores?
- Em quais situações decidiu manter o nulo?

## 6. Batalha 3 — O ataque dos clones (duplicidades)

A aula alerta que nem toda duplicidade é erro automático: pode haver compra legítima repetida ou dupla inserção do sistema. fileciteturn2file0

### Tarefa
1. Investigue se há linhas duplicadas
2. Analise se a duplicidade parece nociva para os KPIs
3. Escolha uma estratégia:
   - remover duplicidades totais?
   - remover apenas com base em certas colunas?
   - manter?
4. Justifique a decisão

In [27]:
# Investigue duplicidades e trate o problema conscientemente
duplicados_antes = df_tratado_nulos.duplicated().sum()

df_sem_duplicados = df_tratado_nulos.drop_duplicates().copy()

duplicados_depois = df_sem_duplicados.duplicated().sum()

print("Duplicados antes:", duplicados_antes)
print("Duplicados depois:", duplicados_depois)

Duplicados antes: 0
Duplicados depois: 0

## 7. Padronização de categorias

Os slides mostram que categorias duplicadas ou mal escritas podem distorcer rankings e filtros. fileciteturn2file0

### Tarefa
Inspecione e padronize, se necessário:
- `uf`
- `canal`
- `categoria`

### Pense em:
- maiúsculas e minúsculas
- espaços extras
- acentuação / variações
- categorias equivalentes escritas de formas diferentes

In [28]:
# Faça aqui a padronização de categorias
df_padronizado = df_sem_duplicados.copy()

if "uf" in df_padronizado.columns:
    df_padronizado["uf"] = df_padronizado["uf"].astype(str).str.strip().str.upper()

if "canal" in df_padronizado.columns:
    canal_base = df_padronizado["canal"].astype(str).str.strip().str.lower()
    df_padronizado["canal"] = canal_base.replace({
        "e-commerce": "E-commerce",
        "e commerce": "E-commerce",
        "ecommerce": "E-commerce",
        "loja fisica": "Loja Física",
        "loja física": "Loja Física",
        "marketplace": "Marketplace",
        "online": "Online"
    })

if "categoria" in df_padronizado.columns:
    df_padronizado["categoria"] = df_padronizado["categoria"].astype(str).str.strip()

if "produto" in df_padronizado.columns:
    df_padronizado["produto"] = df_padronizado["produto"].astype(str).str.strip()

if "canal" in df_padronizado.columns:
    canais_padronizados = df_padronizado["canal"].value_counts(dropna=False)
    print(canais_padronizados)

if "uf" in df_padronizado.columns:
    ufs_padronizadas = df_padronizado["uf"].value_counts(dropna=False)
    print()
    print(ufs_padronizadas)

canal
Loja Física    2
Marketplace    1
Name: count, dtype: int64

uf
SP    1
MG    1
RS    1
Name: count, dtype: int64

## 8. Subindo de nível — Criação de variáveis derivadas

Depois da limpeza, é hora de enriquecer a base com variáveis úteis para análise. fileciteturn2file0

### Tarefa
Crie, se possível:
- `ano`
- `mes`
- `ano_mes`
- `margem_lucro`

### Atenção
A criação de `margem_lucro` exige cuidado com divisões por zero e possíveis valores infinitos.

In [29]:
# Crie aqui as variáveis derivadas
df_enriquecido = df_padronizado.copy()

df_enriquecido["ano"] = df_enriquecido["data"].dt.year
df_enriquecido["mes"] = df_enriquecido["data"].dt.to_period("M").astype(str)

if "lucro" in df_enriquecido.columns:
    df_enriquecido["margem_lucro"] = np.where(
        df_enriquecido["receita"] > 0,
        df_enriquecido["lucro"] / df_enriquecido["receita"],
        np.nan
    )

print(df_enriquecido.head())

     pedido_id       data  uf        canal    categoria       produto  \
0         1000 2024-04-29  SP  Loja Física  Informática  Notebook Pro
101       1101 2024-10-21  MG  Marketplace    Telefonia  Smartphone X
154       1154 2024-09-30  RS  Loja Física  Informática  Notebook Pro

    cliente_id  quantidade       receita         lucro observacao   ano  \
0         C134           1  4.535110e+13  1.289830e+13         ok  2024
101       C151           4  1.146636e+14  2.087050e+13        NaN  2024
154       C155           1  3.998830e+13  6.415400e+12        NaN  2024

         mes  margem_lucro
0    2024-04      0.284410
101  2024-10      0.182015
154  2024-09      0.160432

### Reflexão técnica
Explique:
1. O que pode acontecer ao calcular margem de lucro quando a receita é zero?
2. Como você decidiu tratar esse caso?

## 9. Seleção final — Menos é mais

A aula propõe que nem toda coluna precisa seguir para a base analítica final. fileciteturn2file0

### Tarefa
Crie um DataFrame final, por exemplo `df_clean` ou `df_dash`, contendo apenas as colunas estritamente necessárias para análises de negócio.

**Sugestão de raciocínio:**
- Quais colunas ajudam a responder perguntas de negócio?
- Quais colunas são operacionais, auxiliares ou dispensáveis?
- O que precisa existir para as próximas aulas de visualização e dashboard?

In [30]:
# Selecione aqui a base final com as colunas escolhidas
colunas_finais = [
    "data",
    "ano",
    "mes",
    "uf",
    "canal",
    "produto",
    "categoria",
    "receita",
    "lucro",
    "margem_lucro"
]

colunas_existentes = [col for col in colunas_finais if col in df_enriquecido.columns]

df_clean = df_enriquecido[colunas_existentes].copy()

print(df_clean.head())

          data   ano      mes  uf        canal       produto    categoria  \
0   2024-04-29  2024  2024-04  SP  Loja Física  Notebook Pro  Informática
101 2024-10-21  2024  2024-10  MG  Marketplace  Smartphone X    Telefonia
154 2024-09-30  2024  2024-09  RS  Loja Física  Notebook Pro  Informática

          receita         lucro  margem_lucro
0    4.535110e+13  1.289830e+13      0.284410
101  1.146636e+14  2.087050e+13      0.182015
154  3.998830e+13  6.415400e+12      0.160432

## 10. Validação final da base limpa

Antes de exportar, faça uma checagem final.

### Verifique:
- os tipos estão corretos?
- ainda há nulos problemáticos?
- ainda há duplicidades nocivas?
- existe algum infinito em `margem_lucro`?
- a base está pronta para ser usada em análises e dashboards?

In [31]:
# Faça aqui a validação final da base limpa
shape_final = df_clean.shape
tipos_finais = df_clean.dtypes
nulos_finais = df_clean.isna().sum()
duplicados_finais = df_clean.duplicated().sum()

print("Shape final:", shape_final)
print()
print("Tipos finais:")
print(tipos_finais)
print()
print("Nulos finais:")
print(nulos_finais)
print()
print("Duplicados finais:", duplicados_finais)
print()
df_clean.info()

Shape final: (3, 10)

Tipos finais:
data            datetime64[us]
ano                      int32
mes                        str
uf                         str
canal                      str
produto                    str
categoria                  str
receita                float64
lucro                  float64
margem_lucro           float64
dtype: object

Nulos finais:
data            0
ano             0
mes             0
uf              0
canal           0
produto         0
categoria       0
receita         0
lucro           0
margem_lucro    0
dtype: int64

Duplicados finais: 0

<class 'pandas.DataFrame'>
Index: 3 entries, 0 to 154
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   data          3 non-null      datetime64[us]
 1   ano           3 non-null      int32
 2   mes           3 non-null      str
 3   uf            3 non-null      str
 4   canal         3 non-null      str
 5   produto       3 non-null      str
 6   categoria     3 non-null      str
 7   receita       3 non-null      float64
 8   lucro         3 non-null      float64
 9   margem_lucro  3 non-null      float64
dtypes: datetime64[us](1), float64(3), int32(1), str(5)
memory usage: 252.0 bytes

## 11. Exportação da base "Clean"

Agora gere o arquivo final da base tratada.

### Tarefa
Exporte sua base limpa com o nome:

`vendas_brasil_aula3_clean.csv`

### Observação
Esse arquivo será o selo de qualidade do seu trabalho desta aula.

In [34]:
# Exporte aqui sua base final sem índice
df_clean.to_csv("../data/output/vendas_brasil_aula3_clean.csv", index=False)

## 12. Conclusão e registro reflexivo

Escreva um pequeno texto respondendo:

1. Quais foram os principais problemas de qualidade encontrados?
2. Qual decisão de limpeza foi mais difícil?
3. Que impacto essas falhas poderiam causar em um dashboard?
4. Por que a etapa de limpeza é considerada a "fundação invisível" do projeto?

## 13. Desafio extra (opcional)

Use sua base limpa para responder rapidamente:

- Qual UF concentra maior receita?
- Qual canal gera maior lucro?
- Existe algum mês com desempenho claramente acima dos demais?

Você pode responder com tabelas simples ou pequenos agrupamentos.

In [35]:
if "uf" in df_clean.columns:
    receita_por_uf = df_clean.groupby("uf")["receita"].sum().sort_values(ascending=False)
    uf_topo = receita_por_uf.index[0]
    receita_uf_topo = receita_por_uf.iloc[0]

    print("UF com maior receita:", uf_topo)
    print("Receita:", round(receita_uf_topo, 2))
    print()

if "canal" in df_clean.columns and "lucro" in df_clean.columns:
    lucro_por_canal = df_clean.groupby("canal")["lucro"].sum().sort_values(ascending=False)
    canal_topo = lucro_por_canal.index[0]
    lucro_canal_topo = lucro_por_canal.iloc[0]

    print("Canal com maior lucro:", canal_topo)
    print("Lucro:", round(lucro_canal_topo, 2))
    print()

if "mes" in df_clean.columns:
    receita_por_mes = df_clean.groupby("mes")["receita"].sum().sort_values(ascending=False)
    mes_topo = receita_por_mes.index[0]
    receita_mes_topo = receita_por_mes.iloc[0]

    print("Mês com melhor desempenho:", mes_topo)
    print("Receita:", round(receita_mes_topo, 2))

UF com maior receita: MG
Receita: 114663600000000.0

Canal com maior lucro: Marketplace
Lucro: 20870500000000.0

Mês com melhor desempenho: 2024-10
Receita: 114663600000000.0